# Generated by Django 6.0.2 on 2026-02-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('admission_year', models.IntegerField()),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_phone', models.CharField(max_length=10)),
                ('student_phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
