# Generated by Django 6.0.2 on 2026-02-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='sub_name',
        ),
    ]
