# Generated by Django 6.0.2 on 2026-09-01 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_admission_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission_year',
            new_name='admission_date',
        ),
    ]
