# Generated by Django 5.2.12 on 2026-05-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('principal', 'Principal'), ('HOD', 'hod'), ('lect', 'Lect'), ('management', 'Management'), ('student', 'Student'), ('teacher', 'Teacher')], max_length=10),
        ),
    ]
