# Generated by Django 6.0.2 on 2026-09-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Principal', 'Principal'), ('HOD', 'hod'), ('Lect', 'Lect'), ('Management', 'Management'), ('student', 'Student'), ('teacher', 'Teacher')], max_length=10),
        ),
    ]
