# Generated by Django 6.0.2 on 2026-03-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=200)),
                ('t_phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
            ],
        ),
    ]
